services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports: 
    - "8080:8080"
    environment: 
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=h2
    
  vault:
    build:
      context: vault/
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"