services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports: 
    - "8080:8080"
    - "9000:9000"
    command: ["start-dev", "--http-relative-path", "/auth"]
    environment: 
    - KC_BOOTSTRAP_ADMIN_USERNAME=admin
    - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin

  vault:
    build:
      context: vault/
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"